[package]
name = "musecode_core"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib"]

[dependencies]
num-rational = { version = "0.4", features = ["serde"] }
num-integer = "0.1"
num-traits = "0.2"
blake3 = "1"
bincode = "1"
dashmap = "5"
serde = { version = "1", features = ["derive"] }
midly = "0.5"

[dev-dependencies]
proptest = "1"
sha2 = "0.10"
